---
name: fossa scanning
on:
  push:
    tags:
    - 'v*'
    branches:
    - 'main'

# Declare default permissions as read only.
permissions: read-all

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.3.1
        with:
          api-key: ${{secrets.FOSSA_API_TOKEN}}
