name: audit-scanner release
on:
  push:
    tags:
    - 'v*'

# Declare default permissions as read only.
permissions: read-all

jobs:
  ci:
    uses: kubewarden/audit-scanner/.github/workflows/ci.yml@main
    permissions: read-all

  container-build:
    uses: kubewarden/audit-scanner/.github/workflows/container-build.yml@main
    permissions:
      id-token: write
      packages: write
  release:
    permissions:
      id-token: write
      contents: write
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - ci
      - container-build
    steps:
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install the bom command
        shell: bash
        run: go install sigs.k8s.io/bom/cmd/bom@v0.2.2

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo TAG_NAME=$(echo ${{ github.ref_name }}) >> $GITHUB_ENV

      - name: Create SBOM file
        shell: bash
        run: |
          bom generate -n https://kubewarden.io/kubewarden.spdx \
            --image "ghcr.io/${{github.repository_owner}}/audit-scanner@${{ needs.container-build.outputs.digest }}" \
            . > audit-scanner-sbom.spdx

      - name: Sign BOM file
        run: |
          cosign sign-blob --output-certificate audit-scanner-sbom.spdx.cert \
            --output-signature audit-scanner-sbom.spdx.sig \
            audit-scanner-sbom.spdx
        env:
          COSIGN_EXPERIMENTAL: 1

      - name: Get latest release tag
        id: get_last_release_tag
        uses: actions/github-script@v6
        with:
          script: |
            let release = await github.rest.repos.getLatestRelease({
               owner: context.repo.owner,
               repo: context.repo.repo,
            });

            if (release.status  === 200 ) {
              core.setOutput('old_release_tag', release.data.tag_name)
              return
            }
            core.setFailed("Cannot find latest release")

      - name: Get release ID from the release created by release drafter
        uses: actions/github-script@v6
        with:
          script: |
            let releases = await github.rest.repos.listReleases({
               owner: context.repo.owner,
               repo: context.repo.repo,
            });
            for (const release of releases.data) {
              if (release.draft) {
                      core.info(release)
                      core.exportVariable('RELEASE_ID', release.id)
                      return
              }
            }
            core.setFailed(`Draft release not found`)

      - name: Upload release assets
        id: upload_release_assets
        uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let files = ['audit-scanner-sbom.spdx', 'audit-scanner-sbom.spdx.cert', 'audit-scanner-sbom.spdx.sig', "CRDS.tar.gz"]
            const {RELEASE_ID} = process.env

            for (const file of files) {
              let file_data = fs.readFileSync(file);

              let response = await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: `${RELEASE_ID}`,
                name: file,
                data: file_data,
              });
              // store the crds asset id used it in the helm chart update
              if (file === "CRDS.tar.gz") {
                core.setOutput('crds_asset_id', response.data.id)
              }
            }

      - name: Publish release
        uses: actions/github-script@v6
        with:
          script: |
            const {RELEASE_ID} = process.env
            const {TAG_NAME} = process.env
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${RELEASE_ID}`,
              draft: false,
              tag_name: `${TAG_NAME}`,
              name: `${TAG_NAME}`
            });

      # TODO
      # - name: Trigger chart update
      #   uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
      #   with:
      #     token: ${{ secrets.HELM_CHART_REPO_ACCESS_TOKEN }}
      #     repository: "${{github.repository_owner}}/helm-charts"
      #     event-type: update-chart
      #     client-payload: '{"version": "${{ github.ref_name }}", "oldVersion": "${{ steps.get_last_release_tag.outputs.old_release_tag }}", "repository": "${{ github.repository }}"}'
